version: 2
updates:
- package-ecosystem: terraform
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: terraform
  directory: "/tests/create_accessanalyzer"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: terraform
  directory: "/tests/create_iam_account"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: terraform
  directory: "/tests/use_all_variables"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
