dist: focal

language: minimal

stages:
  - lint
  - test
  - deploy

if: branch = master OR type = pull_request

before_install:
  - tmpdaemon=$(mktemp)
  - sudo jq '."registry-mirrors" += ["https://mirror.gcr.io"]' /etc/docker/daemon.json > "$tmpdaemon"
  - sudo mv "$tmpdaemon" /etc/docker/daemon.json
  - sudo systemctl daemon-reload
  - sudo systemctl restart docker
  - docker system info

jobs:
  include:
    - stage: lint
      name: Project Syntax Verification
      script: make docker/run target=lint
    - stage: test
      name: Apply Terraform test configs in mockstack
      install:
        - make docker-compose/install
        - make mockstack/up
      script: make mockstack/pytest
      after_script:
        - make mockstack/clean
    - stage: deploy
      if: branch = master AND type = push AND repo = plus3it/terraform-aws-tardigrade-iam-account
      before_script:
        - |
          PRIOR_VERSION=$(git describe --abbrev=0 --tags)
          RELEASE_VERSION=$(grep current_version $TRAVIS_BUILD_DIR/.bumpversion.cfg | sed 's/^.*= //' )
          RELEASE_BODY="* [terraform-aws-tardigrade-iam-account v$RELEASE_VERSION CHANGELOG](https://github.com/plus3it/terraform-aws-tardigrade-iam-account/blob/$RELEASE_VERSION/CHANGELOG.md)"
          export PRIOR_VERSION RELEASE_VERSION RELEASE_BODY
      script: skip
      before_deploy:
        - |
          (set -x; git tag -a $RELEASE_VERSION -m $RELEASE_VERSION)
      deploy:
        provider: releases
        api_key:
          secure: cv3xVPQehrOSwfqYvXYIxvuCtKYPnX6nhGPoVb2jrrKcQPMZheBc4FDXA4Vp8Y9M9NgyIXRl6g6gCwKMElbgSgasCuMV8C9e01Or2W4QuGPn4/u7O5jXolNS41gMmSTcezSu8LRGcTSkKc1hLCSJPulWEXx0/Qg/obQAso9PsWgYlHcsf0TIHHuvQ4FwksXLLMXPxC86Y7/svWGooC0F7k6vpPMCf8HQ/66iChX2El2VSDF0rabNhfdf+9qKgsUS92vf3UHWuL3fl8GXc2lFBvtZlQlil8S04QTj59xl5qreZXiBKuyeYnw08Qkw6vE8xiqUAQe9hcOlcPXFKvs0iL+5PCFJuGhIZuX+uBkqz9zQdCLm/45h/TTz3XIa6fo4EMol+XXTR8l9xGkch71WV9Sv1EypHg2JSjyNab9dipyINaMXSrDwoVKm4Uz4is0cQWVUK+NX3XAgZpXingTWc8n5SUTqfv91WYkJTCajGlWBN/owDS1ulu+12uC64TkaVtnqbYYGV2cJGkMZf5A3okl4HGbaiulBhVOxQ8w78+horGDx9BiD3q+FjbG/8sPA+t42WY3ScmCW13h5BPRg372pkaDAN/eQ82p+IwNQWIWTufLmB5pFJrwLK/LU3af1N2UFUMQ+domc1Iwl62dMptYOKMoHBwn2ILvdrwCMR88=
        name: $RELEASE_VERSION
        body: $RELEASE_BODY
        tag_name: $RELEASE_VERSION
        target_commitish: $TRAVIS_COMMIT
        draft: false
        on:
          branch: master
          repo: plus3it/terraform-aws-tardigrade-iam-account
          condition: '"$PRIOR_VERSION" != "$RELEASE_VERSION"'
